var searchData=
[
  ['savesegment_5ft',['SaveSegment_t',['../structSaveSegment__t.html',1,'']]],
  ['scopedthreadpriority_5fc',['ScopedThreadPriority_c',['../classScopedThreadPriority__c.html',1,'']]],
  ['searchdstats_5ft',['SearchdStats_t',['../structSearchdStats__t.html',1,'']]],
  ['searchfailure_5ft',['SearchFailure_t',['../structSearchFailure__t.html',1,'']]],
  ['searchfailureslog_5fc',['SearchFailuresLog_c',['../classSearchFailuresLog__c.html',1,'']]],
  ['searchhandler_5fc',['SearchHandler_c',['../classSearchHandler__c.html',1,'']]],
  ['searchreplyparser_5ft',['SearchReplyParser_t',['../structSearchReplyParser__t.html',1,'']]],
  ['searchrequestbuilder_5ft',['SearchRequestBuilder_t',['../structSearchRequestBuilder__t.html',1,'']]],
  ['selectbounds_5ft',['SelectBounds_t',['../structSelectBounds__t.html',1,'']]],
  ['selectevents_5fc',['SelectEvents_c',['../classSelectEvents__c.html',1,'']]],
  ['selectparser_5ft',['SelectParser_t',['../classSelectParser__t.html',1,'']]],
  ['serveddesc_5ft',['ServedDesc_t',['../structServedDesc__t.html',1,'']]],
  ['servedindex_5fc',['ServedIndex_c',['../classServedIndex__c.html',1,'']]],
  ['servedstats_5fc',['ServedStats_c',['../classServedStats__c.html',1,'']]],
  ['sessionvars_5ft',['SessionVars_t',['../structSessionVars__t.html',1,'']]],
  ['skiplistentry_5ft',['SkiplistEntry_t',['../structSkiplistEntry__t.html',1,'']]],
  ['slice64_5ft',['Slice64_t',['../structSlice64__t.html',1,'']]],
  ['slice_5ft',['Slice_t',['../structSlice__t.html',1,'']]],
  ['sliceint_5ft',['SliceInt_t',['../structSliceInt__t.html',1,'']]],
  ['smallstringhash_5ft',['SmallStringHash_T',['../classSmallStringHash__T.html',1,'']]],
  ['smallstringhash_5ft_3c_20csphconfigtype_20_3e',['SmallStringHash_T&lt; CSphConfigType &gt;',['../classSmallStringHash__T.html',1,'']]],
  ['smallstringhash_5ft_3c_20csphstring_20_3e',['SmallStringHash_T&lt; CSphString &gt;',['../classSmallStringHash__T.html',1,'']]],
  ['smallstringhash_5ft_3c_20csphvariant_20_3e',['SmallStringHash_T&lt; CSphVariant &gt;',['../classSmallStringHash__T.html',1,'']]],
  ['smallstringhash_5ft_3c_20int_20_3e',['SmallStringHash_T&lt; int &gt;',['../classSmallStringHash__T.html',1,'']]],
  ['smallstringhash_5ft_3c_20int64_5ft_20_3e',['SmallStringHash_T&lt; int64_t &gt;',['../classSmallStringHash__T.html',1,'']]],
  ['smallstringhash_5ft_3c_20servedindex_5fc_20_3e',['SmallStringHash_T&lt; ServedIndex_c &gt;',['../classSmallStringHash__T.html',1,'']]],
  ['smallstringhash_5ft_3c_20wordstat_5ft_20_3e',['SmallStringHash_T&lt; WordStat_t &gt;',['../classSmallStringHash__T.html',1,'']]],
  ['snippetcontext_5ft',['SnippetContext_t',['../classSnippetContext__t.html',1,'']]],
  ['snippetreplyparser_5ft',['SnippetReplyParser_t',['../structSnippetReplyParser__t.html',1,'']]],
  ['snippetrequestbuilder_5ft',['SnippetRequestBuilder_t',['../structSnippetRequestBuilder__t.html',1,'']]],
  ['snippetsdocindex_5fc',['SnippetsDocIndex_c',['../classSnippetsDocIndex__c.html',1,'']]],
  ['snippetsfastqword_5fc',['SnippetsFastQword_c',['../classSnippetsFastQword__c.html',1,'']]],
  ['snippetsfastqwordsetup_5fc',['SnippetsFastQwordSetup_c',['../classSnippetsFastQwordSetup__c.html',1,'']]],
  ['snippetsremote_5ft',['SnippetsRemote_t',['../structSnippetsRemote__t.html',1,'']]],
  ['snippetthread_5ft',['SnippetThread_t',['../structSnippetThread__t.html',1,'']]],
  ['snippetworker_5ft',['SnippetWorker_t',['../structSnippetWorker__t.html',1,'']]],
  ['snippetzonechecker_5fc',['SnippetZoneChecker_c',['../classSnippetZoneChecker__c.html',1,'']]],
  ['sortclausetokenizer_5ft',['SortClauseTokenizer_t',['../classSortClauseTokenizer__t.html',1,'']]],
  ['sortdatagendesc_5ft',['SortDataGenDesc_t',['../structSortDataGenDesc__t.html',1,'']]],
  ['sortedremapxsv_5ft',['SortedRemapXSV_t',['../structSortedRemapXSV__t.html',1,'']]],
  ['sortpayload_5ft',['SortPayload_t',['../structSortPayload__t.html',1,'']]],
  ['space_5ft',['Space_t',['../structSpace__t.html',1,'']]],
  ['spantoken_5ft',['SpanToken_t',['../structSpanToken__t.html',1,'']]],
  ['sphaccessor_5ft',['SphAccessor_T',['../structSphAccessor__T.html',1,'']]],
  ['sphaccessor_5ft_3c_20csphmatch_20_3e',['SphAccessor_T&lt; CSphMatch &gt;',['../structSphAccessor__T.html',1,'']]],
  ['sphcheckpointaccess_5ffn',['SphCheckpointAccess_fn',['../structSphCheckpointAccess__fn.html',1,'']]],
  ['sphchunkguard_5ft',['SphChunkGuard_t',['../structSphChunkGuard__t.html',1,'']]],
  ['sphcrashlogger_5fc',['SphCrashLogger_c',['../classSphCrashLogger__c.html',1,'']]],
  ['sphdocrandomizer_5fc',['SphDocRandomizer_c',['../classSphDocRandomizer__c.html',1,'']]],
  ['sphexpanded_5ft',['SphExpanded_t',['../structSphExpanded__t.html',1,'']]],
  ['sphextradatarankerstate_5ft',['SphExtraDataRankerState_t',['../structSphExtraDataRankerState__t.html',1,'']]],
  ['sphfactorhashentry_5ft',['SphFactorHashEntry_t',['../structSphFactorHashEntry__t.html',1,'']]],
  ['sphfinalarenacopy_5ft',['SphFinalArenaCopy_t',['../structSphFinalArenaCopy__t.html',1,'']]],
  ['sphfinalmatchcalc_5ft',['SphFinalMatchCalc_t',['../structSphFinalMatchCalc__t.html',1,'']]],
  ['sphfinalmatchcopy_5ft',['SphFinalMatchCopy_t',['../structSphFinalMatchCopy__t.html',1,'']]],
  ['sphfinalmatchcounter_5ft',['SphFinalMatchCounter_t',['../structSphFinalMatchCounter__t.html',1,'']]],
  ['sphgreater_5ft',['SphGreater_T',['../structSphGreater__T.html',1,'']]],
  ['sphgroupedvalue_5ft',['SphGroupedValue_t',['../structSphGroupedValue__t.html',1,'']]],
  ['sphhitmark_5ft',['SphHitMark_t',['../structSphHitMark__t.html',1,'']]],
  ['sphidentityfunctor_5ft',['SphIdentityFunctor_T',['../structSphIdentityFunctor__T.html',1,'']]],
  ['sphinxqlreplyparser_5ft',['SphinxqlReplyParser_t',['../structSphinxqlReplyParser__t.html',1,'']]],
  ['sphinxqlrequestbuilder_5ft',['SphinxqlRequestBuilder_t',['../structSphinxqlRequestBuilder__t.html',1,'']]],
  ['sphless_5ft',['SphLess_T',['../structSphLess__T.html',1,'']]],
  ['sphmemberfunctor_5ft',['SphMemberFunctor_T',['../structSphMemberFunctor__T.html',1,'']]],
  ['sphmemberless_5ft',['SphMemberLess_T',['../structSphMemberLess__T.html',1,'']]],
  ['sphoptimizeguard_5ft',['SphOptimizeGuard_t',['../structSphOptimizeGuard__t.html',1,'']]],
  ['sphqueuesettings_5ft',['SphQueueSettings_t',['../structSphQueueSettings__t.html',1,'']]],
  ['sphrange_5ft',['SphRange_t',['../structSphRange__t.html',1,'']]],
  ['sphrtfinalmatchcalc_5ft',['SphRtFinalMatchCalc_t',['../structSphRtFinalMatchCalc__t.html',1,'']]],
  ['sphstringbuilder_5ft',['SphStringBuilder_T',['../classSphStringBuilder__T.html',1,'']]],
  ['sphstringbuilder_5ft_3c_20escapequotation_5ft_20_3e',['SphStringBuilder_T&lt; EscapeQuotation_t &gt;',['../classSphStringBuilder__T.html',1,'']]],
  ['sphstringsorterremap_5ft',['SphStringSorterRemap_t',['../structSphStringSorterRemap__t.html',1,'']]],
  ['sphtestdoc_5fc',['SphTestDoc_c',['../classSphTestDoc__c.html',1,'']]],
  ['sphungroupedvalue_5ft',['SphUngroupedValue_t',['../structSphUngroupedValue__t.html',1,'']]],
  ['sphwordstatchecker_5ft',['SphWordStatChecker_t',['../structSphWordStatChecker__t.html',1,'']]],
  ['split_5ft',['Split_t',['../structSplit__t.html',1,'']]],
  ['sqlinsert_5ft',['SqlInsert_t',['../structSqlInsert__t.html',1,'']]],
  ['sqlnode_5ft',['SqlNode_t',['../structSqlNode__t.html',1,'']]],
  ['sqlparser_5fc',['SqlParser_c',['../structSqlParser__c.html',1,'']]],
  ['sqlrowbuffer_5fc',['SqlRowBuffer_c',['../classSqlRowBuffer__c.html',1,'']]],
  ['sqlstmt_5ft',['SqlStmt_t',['../structSqlStmt__t.html',1,'']]],
  ['st_5fplugin_5fhit',['st_plugin_hit',['../structst__plugin__hit.html',1,'']]],
  ['st_5fplugin_5frankerinfo',['st_plugin_rankerinfo',['../structst__plugin__rankerinfo.html',1,'']]],
  ['st_5fsphinx_5ffactors',['st_sphinx_factors',['../structst__sphinx__factors.html',1,'']]],
  ['st_5fsphinx_5ffield_5ffactors',['st_sphinx_field_factors',['../structst__sphinx__field__factors.html',1,'']]],
  ['st_5fsphinx_5fterm_5ffactors',['st_sphinx_term_factors',['../structst__sphinx__term__factors.html',1,'']]],
  ['st_5fsphinx_5fudf_5fargs',['st_sphinx_udf_args',['../structst__sphinx__udf__args.html',1,'']]],
  ['st_5fsphinx_5fudf_5finit',['st_sphinx_udf_init',['../structst__sphinx__udf__init.html',1,'']]],
  ['stacknode_5ft',['StackNode_t',['../structStackNode__t.html',1,'']]],
  ['state_5ft',['State_t',['../structFSMphrase_1_1State__t.html',1,'FSMphrase']]],
  ['statsperquery_5ft',['StatsPerQuery_t',['../structStatsPerQuery__t.html',1,'']]],
  ['storagemvavector_5ft',['StorageMvaVector_t',['../classStorageMvaVector__t.html',1,'']]],
  ['storagemvawriter_5ft',['StorageMvaWriter_t',['../classStorageMvaWriter__t.html',1,'']]],
  ['storagestringvector_5ft',['StorageStringVector_t',['../classStorageStringVector__t.html',1,'']]],
  ['storagestringwriter_5ft',['StorageStringWriter_t',['../classStorageStringWriter__t.html',1,'']]],
  ['storedexcerpttoken_5ft',['StoredExcerptToken_t',['../structStoredExcerptToken__t.html',1,'']]],
  ['storedtoken_5ft',['StoredToken_t',['../structStoredToken__t.html',1,'']]],
  ['strippertag_5ft',['StripperTag_t',['../structCSphHTMLStripper_1_1StripperTag__t.html',1,'CSphHTMLStripper']]],
  ['suggestargs_5ft',['SuggestArgs_t',['../structSuggestArgs__t.html',1,'']]],
  ['suggestresult_5ft',['SuggestResult_t',['../structSuggestResult__t.html',1,'']]],
  ['suggestword_5ft',['SuggestWord_t',['../structSuggestWord__t.html',1,'']]],
  ['symboldesc_5ft',['SymbolDesc_t',['../structSymbolDesc__t.html',1,'']]]
];
